---
abstract: 'Down Translator (XML::DT) for sequence XMLs'
author:
  - 'Alberto Simões <ambs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-DT-Sequence
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  XML::DT: 0.62
version: 0.01
